spin_manifest_version = "1"
authors = ["Morgante Pell <me@morgante.net>"]
description = "sample-spin"
name = "sampler"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "sampler"
source = "target/sampler.wasm"
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
